[workspace]
resolver = "3"
members = ["crates/habit-kernel-cli","crates/habit-kernel-core"]

[workspace.package]
description = "`HabitKernel` is an open‑source habit manager. Create, mark, and edit your habits without restrictions."
edition = "2024"
rust-version = "1.98.0"
authors = ["0xDimay <HexDimay@yandex.ru>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.0.1"


[workspace.dependencies]
habit-kernel-core = { path = "./crates/habit-kernel-core" }

chrono = { version = "0.4.45", features = ["serde"] }
anyhow = "1.0.104"
uuid = { version = "1.26.1", features = ["v4", "serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
basic-toml = "0.1.10"