[package]
name = "habit-kernel-cli"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
clap_derive = "4.6.7"
anyhow = { workspace = true }
habit-kernel-core = { workspace = true }
uuid = { workspace = true }

cli-table = "0.5.0"